# This is a basic workflow to help you get started with Actions

name: Call workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 get-action:
    runs-on: ubuntu-latest
    steps:    
      - name: Get Action 
        id: foo
        uses:  TeddyBrod/Composite-action@main
        with:
          who-to-greet: "Fred"
          duck_token: "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"

 cat-scripts:
   needs: get-action
   uses: TeddyBrod/workflow-script/.github/workflows/workflow_call.yml@main



